FROM node:lts-alpine as baseImage
LABEL author="hopeswiller_<davidba941@gmail.com>"
LABEL version="0.1.0"
LABEL name="url-shortener"

# install simple http server for serving static content
RUN npm install -g http-server

WORKDIR /app

COPY package*.json ./

RUN npm install
COPY . .

# build app for production with minification
RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]